### ISSUE TITLE
Working Prototype

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#10]
A working prototype of the system must be physically implemented. The prototype must allow the sensor to detect the weight of a shelf so that the sensor can communicate the necessary information to the raspberry pi server. The prototype must take into account that the raspberry pi is connected to the sensor via USB.

**Tasks breakdown**
- [ ] Design a prototype where the sensor will hold the weight of a shelf and read the correct weight data.

**Implementation details**
- [ ] The system must be stable and allow the user to place items anywhere on the shelf.

**Verification/Testing**
- [ ] The sensor must read the accurate weight from the combined weight of the shelf and the items
