### ISSUE TITLE
Amazon Dash Button

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#11]
We must add a component on the user interface to allow a user to re-order items

[Value: High] Required to re-order products

[Risk: Medium] 

Tasks breakdown

**Tasks breakdown**
- [ ] The API must be added to the project
- [ ] A front-end component in the UI must allow the user to use the dash button features

**Implementation details**
- [ ] Add a button to allow the client to re-order
- [ ] When the button is clicked, a request must be sent to the server to order more items

**Verification/Testing**
- [ ] The server must receive a request to re-order a specific item when a user clicks on the amazon dash button
