### ISSUE TITLE
Server-side Amazon Dash button

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#12]
After receiving a request from the client-side, the server must use the Amazon Dash Button API to order more items

[Risk: Medium] 

Tasks breakdown

**Tasks breakdown**
- [ ] The API must be added to the server-side and
- [ ] A re-order product functionality must be implemented

**Implementation details**
- [ ] Import the API
- [ ] Create function to re-order an item from amazon

**Verification/Testing**
- [ ] The server must receive a request to re-order a specific item and must be able to re-order an item directly from amazon
