### ISSUE TITLE
Re-ordering notification system

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#13]
The server must be able to read the weight from the sensor and if the weight is too low, it must send a notification to the user to tell him more items will be ordered. The user has X minutes to cancel re-ordering. If the user does not cancel, the missing item will be re-ordered.

**Tasks breakdown**
- [ ] The server must read the sensor's weight
- [ ] The server must send a notification to the client to notify that new items will be ordered. When the notification is sent the user will send back a confirm or cancel response.

**Implementation details**
- [ ] Define weight at which the server sends the notification 
- [ ] The server must send a notification to the client-side to warn that new items will be ordered
- [ ] The server must must wait and receive a confirm or cancel response from the client-side. If a confirm response is received, new items must be ordered

**Verification/Testing**
- [ ] The server must be able to determine when the weight is too low, send a notification to the user and re-order more products
