### ISSUE TITLE
Re-order notification interface

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#14]
When the weight on the sensor is too low, the server sends a notification to warn that new items will be ordered. The user interface must display a notification to the user and allow him to cancel the order if he wants to cancel. The interface must also display a timer during which cancellation is possible. After the timer expires, the notification will disappear and a new order request will be sent back to the server.

**Tasks breakdown**
- [ ] Make a UI component that will notify the client that new items will be ordered
- [ ] Implement a timer after which the UI component will disappear and new items will be ordered
- [ ] The UI component must allow the user to cancel the order

**Implementation details**
- [ ] Make UI component that allows the user to accept or cancel an order
- [ ] Add a timer to the UI component. If the timer runs out, new items will be ordered
- [ ] If the user accepts the order or the timer runs out, a request must be sent to the server to order new items.
- [ ] If the user cancels the order, a request must be sent to the server to notify that the user does not want to order more items.

**Verification/Testing**
- [ ] When the client-side receives a notification from the server indicating that the weight is too low, a notification displays on the UI asking the user if they want to cancel the order or not.
