### ISSUE TITLE
Backend Summary

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#6]
List of all Backend tasks (server-side):

- [ ] #7 Server set up
- [ ] #12 Amazon Dash Button API
- [ ] #13 Client-side notification of order
