### ISSUE TITLE
Server set up

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#7]
The raspberry pi must be set up and connected to the sensor. We must run a server on the raspberry pi that will connect to the client's device.

[Value: High] Required to communicate from the sensor to the client and to order online

[Risk: High] Need to be done properly the system may not be able to run

**Tasks breakdown**
- [ ] Set up raspberry pi with the sensor
- [ ] Install and run server on the raspberry pi
- [ ] Verify that the raspberry pi can communicate with the sensor

**Implementation details**
- [ ] The sensor must be connected to the raspberry pi via USB 
- [x] The server will be implemented using python (ex. Flask, Django, ....)
- [ ] Install the sensor software (WinCT) on the raspberry pi to communicate with the sensor

**Verification/Testing**
- [ ] We must be able to send and receive test data from the sensor
