### ISSUE TITLE
Frontend Summary

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#8]
All tasks related to frontend (client-side):

- [ ] #9 Main client UI 
- [ ] #11 Amazon Dash Button
- [ ] #14 UI notification for re-ordering items
