### ISSUE TITLE
Client Main UI

### ISSUE THREAD

**Issue by ONourry** [kyudai-pbl1-2020/PBL#9]
We must design and implement the main UI of the software that will be used by the user on his personal device. 

[Value: High] Required to allow the user to  tell the system what items to order

[Risk: Medium]

**Tasks breakdown**
- [ ] Think of a design that makes the software easy to use with the following specifications
- - [ ] The UI must allow the user to register a new item on the main UI
- - [ ] The UI must allow the user to see the list of current items in the database
- - [ ] The UI must allow the user to edit/modify existing items in the database

**Note**
The interface must be easy to read and use. If it becomes too complicated to use, extract the functionalities to another page or menu and redirect the user to this other page.

**Implementation details**
- [x] A graphics library must be chosen and installed to implement the user interface
- [ ] The layout of the UI must be designed and implemented

**Verification/Testing**
- [ ] We must have a running application window with the selected UI design implemented
